import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <script>
          {`
  window.chatbotConfig = {
    domain: 'https://api.llamaworx.com/',
    apiKey: 'your-api-key-here',
    };
    `}
        </script>
        <script src="/embed.js" />
      </body>
    </html>
  );
}

// primaryColor: '#10B981',
// position: 'bottom-right',
// welcomeMessage: 'Welcome! How can we help you?',
// speechRecognition: true,
// speechLanguage: 'en-US'